nodeLinker: node-modules
enableGlobalCache: true
checksumBehavior: throw

packageExtensions:
  "medusa-plugin-razorpay-v2@*":
    peerDependencies:
      "@medusajs/admin-sdk": ">=2.7.1 <3"
      "@medusajs/test-utils": ">=2.7.1 <3"
      "@medusajs/framework": ">=2.7.1 <3"
      "@medusajs/medusa": ">=2.7.1 <3"
